networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build: ./backend
    environment:
      - YANDEX_EMAIL=powerman.2003@yandex.ru
      - YANDEX_PASSWORD=228PAROL228
    networks:
      - dev
