services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - YANDEX_EMAIL=powerman.2003@yandex.ru
      - YANDEX_PASSWORD=228PAROL228
    ports:
      - "5000:5000"